/**
 * Language list covering all 100 languages supported by M2M-100
 * (and the majority of NLLB-200). Sorted alphabetically by name.
 * BCP-47 codes used throughout.
 */
export const LANGUAGES = [
	{ code: 'af', name: 'Afrikaans' },
	{ code: 'sq', name: 'Albanian' },
	{ code: 'am', name: 'Amharic' },
	{ code: 'ar', name: 'Arabic' },
	{ code: 'hy', name: 'Armenian' },
	{ code: 'az', name: 'Azerbaijani' },
	{ code: 'be', name: 'Belarusian' },
	{ code: 'bn', name: 'Bengali' },
	{ code: 'bs', name: 'Bosnian' },
	{ code: 'bg', name: 'Bulgarian' },
	{ code: 'my', name: 'Burmese' },
	{ code: 'ca', name: 'Catalan' },
	{ code: 'ceb', name: 'Cebuano' },
	{ code: 'zh', name: 'Chinese (Simplified)' },
	{ code: 'hr', name: 'Croatian' },
	{ code: 'cs', name: 'Czech' },
	{ code: 'da', name: 'Danish' },
	{ code: 'nl', name: 'Dutch' },
	{ code: 'en', name: 'English' },
	{ code: 'et', name: 'Estonian' },
	{ code: 'tl', name: 'Filipino' },
	{ code: 'fi', name: 'Finnish' },
	{ code: 'fr', name: 'French' },
	{ code: 'gl', name: 'Galician' },
	{ code: 'ka', name: 'Georgian' },
	{ code: 'de', name: 'German' },
	{ code: 'el', name: 'Greek' },
	{ code: 'gu', name: 'Gujarati' },
	{ code: 'ht', name: 'Haitian Creole' },
	{ code: 'ha', name: 'Hausa' },
	{ code: 'he', name: 'Hebrew' },
	{ code: 'hi', name: 'Hindi' },
	{ code: 'hu', name: 'Hungarian' },
	{ code: 'is', name: 'Icelandic' },
	{ code: 'ig', name: 'Igbo' },
	{ code: 'id', name: 'Indonesian' },
	{ code: 'ga', name: 'Irish' },
	{ code: 'it', name: 'Italian' },
	{ code: 'ja', name: 'Japanese' },
	{ code: 'jv', name: 'Javanese' },
	{ code: 'kn', name: 'Kannada' },
	{ code: 'kk', name: 'Kazakh' },
	{ code: 'km', name: 'Khmer' },
	{ code: 'ko', name: 'Korean' },
	{ code: 'lo', name: 'Lao' },
	{ code: 'lv', name: 'Latvian' },
	{ code: 'lt', name: 'Lithuanian' },
	{ code: 'mk', name: 'Macedonian' },
	{ code: 'ms', name: 'Malay' },
	{ code: 'ml', name: 'Malayalam' },
	{ code: 'mr', name: 'Marathi' },
	{ code: 'mn', name: 'Mongolian' },
	{ code: 'ne', name: 'Nepali' },
	{ code: 'no', name: 'Norwegian' },
	{ code: 'or', name: 'Odia' },
	{ code: 'ps', name: 'Pashto' },
	{ code: 'fa', name: 'Persian' },
	{ code: 'pl', name: 'Polish' },
	{ code: 'pt', name: 'Portuguese' },
	{ code: 'pa', name: 'Punjabi' },
	{ code: 'ro', name: 'Romanian' },
	{ code: 'ru', name: 'Russian' },
	{ code: 'sr', name: 'Serbian' },
	{ code: 'si', name: 'Sinhala' },
	{ code: 'sk', name: 'Slovak' },
	{ code: 'sl', name: 'Slovenian' },
	{ code: 'so', name: 'Somali' },
	{ code: 'es', name: 'Spanish' },
	{ code: 'su', name: 'Sundanese' },
	{ code: 'sw', name: 'Swahili' },
	{ code: 'sv', name: 'Swedish' },
	{ code: 'ta', name: 'Tamil' },
	{ code: 'te', name: 'Telugu' },
	{ code: 'th', name: 'Thai' },
	{ code: 'tr', name: 'Turkish' },
	{ code: 'uk', name: 'Ukrainian' },
	{ code: 'ur', name: 'Urdu' },
	{ code: 'uz', name: 'Uzbek' },
	{ code: 'vi', name: 'Vietnamese' },
	{ code: 'cy', name: 'Welsh' },
	{ code: 'xh', name: 'Xhosa' },
	{ code: 'yi', name: 'Yiddish' },
	{ code: 'yo', name: 'Yoruba' },
	{ code: 'zu', name: 'Zulu' },
] as const;

export const LANGUAGE_FORMATS = [
	{ value: 'bcp47', label: 'BCP-47' },
	{ value: 'native', label: 'Native' },
] as const;
