/**
 * Language list covering all languages supported by NLLB-200
 * (and the majority of M2M-100). BCP-47 / ISO 639 codes used throughout.
 * Sorted alphabetically by name.
 */
export const LANGUAGES = [
	{ code: 'ace', name: 'Acehnese' },
	{ code: 'af', name: 'Afrikaans' },
	{ code: 'sq', name: 'Albanian' },
	{ code: 'am', name: 'Amharic' },
	{ code: 'ar', name: 'Arabic' },
	{ code: 'ary', name: 'Arabic (Moroccan)' },
	{ code: 'arz', name: 'Arabic (Egyptian)' },
	{ code: 'hy', name: 'Armenian' },
	{ code: 'as', name: 'Assamese' },
	{ code: 'ast', name: 'Asturian' },
	{ code: 'awa', name: 'Awadhi' },
	{ code: 'ay', name: 'Aymara' },
	{ code: 'az', name: 'Azerbaijani' },
	{ code: 'ban', name: 'Balinese' },
	{ code: 'bm', name: 'Bambara' },
	{ code: 'bjn', name: 'Banjar' },
	{ code: 'ba', name: 'Bashkir' },
	{ code: 'eu', name: 'Basque' },
	{ code: 'be', name: 'Belarusian' },
	{ code: 'bem', name: 'Bemba' },
	{ code: 'bn', name: 'Bengali' },
	{ code: 'bho', name: 'Bhojpuri' },
	{ code: 'bo', name: 'Tibetan' },
	{ code: 'bs', name: 'Bosnian' },
	{ code: 'bug', name: 'Buginese' },
	{ code: 'bg', name: 'Bulgarian' },
	{ code: 'my', name: 'Burmese' },
	{ code: 'ca', name: 'Catalan' },
	{ code: 'ceb', name: 'Cebuano' },
	{ code: 'hne', name: 'Chhattisgarhi' },
	{ code: 'yue', name: 'Chinese (Cantonese)' },
	{ code: 'zh', name: 'Chinese (Simplified)' },
	{ code: 'zh-Hant', name: 'Chinese (Traditional)' },
	{ code: 'cv', name: 'Chuvash' },
	{ code: 'hr', name: 'Croatian' },
	{ code: 'cs', name: 'Czech' },
	{ code: 'da', name: 'Danish' },
	{ code: 'din', name: 'Dinka' },
	{ code: 'nl', name: 'Dutch' },
	{ code: 'dyu', name: 'Dyula' },
	{ code: 'dz', name: 'Dzongkha' },
	{ code: 'en', name: 'English' },
	{ code: 'eo', name: 'Esperanto' },
	{ code: 'et', name: 'Estonian' },
	{ code: 'ee', name: 'Ewe' },
	{ code: 'fao', name: 'Faroese' },
	{ code: 'tl', name: 'Filipino' },
	{ code: 'fi', name: 'Finnish' },
	{ code: 'fj', name: 'Fijian' },
	{ code: 'fon', name: 'Fon' },
	{ code: 'fr', name: 'French' },
	{ code: 'fur', name: 'Friulian' },
	{ code: 'ff', name: 'Fulah' },
	{ code: 'gl', name: 'Galician' },
	{ code: 'lg', name: 'Ganda' },
	{ code: 'ka', name: 'Georgian' },
	{ code: 'de', name: 'German' },
	{ code: 'el', name: 'Greek' },
	{ code: 'gn', name: 'Guarani' },
	{ code: 'gu', name: 'Gujarati' },
	{ code: 'ht', name: 'Haitian Creole' },
	{ code: 'ha', name: 'Hausa' },
	{ code: 'he', name: 'Hebrew' },
	{ code: 'hi', name: 'Hindi' },
	{ code: 'hu', name: 'Hungarian' },
	{ code: 'is', name: 'Icelandic' },
	{ code: 'ig', name: 'Igbo' },
	{ code: 'ilo', name: 'Ilocano' },
	{ code: 'id', name: 'Indonesian' },
	{ code: 'ga', name: 'Irish' },
	{ code: 'it', name: 'Italian' },
	{ code: 'ja', name: 'Japanese' },
	{ code: 'jv', name: 'Javanese' },
	{ code: 'kab', name: 'Kabyle' },
	{ code: 'kbp', name: 'Kabiyè' },
	{ code: 'kea', name: 'Kabuverdianu' },
	{ code: 'kn', name: 'Kannada' },
	{ code: 'ks', name: 'Kashmiri' },
	{ code: 'kk', name: 'Kazakh' },
	{ code: 'km', name: 'Khmer' },
	{ code: 'ki', name: 'Kikuyu' },
	{ code: 'rw', name: 'Kinyarwanda' },
	{ code: 'kmb', name: 'Kimbundu' },
	{ code: 'kg', name: 'Kongo' },
	{ code: 'ko', name: 'Korean' },
	{ code: 'ckb', name: 'Kurdish (Sorani)' },
	{ code: 'kmr', name: 'Kurdish (Kurmanji)' },
	{ code: 'ky', name: 'Kyrgyz' },
	{ code: 'lo', name: 'Lao' },
	{ code: 'ltg', name: 'Latgalian' },
	{ code: 'lv', name: 'Latvian' },
	{ code: 'lb', name: 'Luxembourgish' },
	{ code: 'lij', name: 'Ligurian' },
	{ code: 'li', name: 'Limburgish' },
	{ code: 'ln', name: 'Lingala' },
	{ code: 'lt', name: 'Lithuanian' },
	{ code: 'lmo', name: 'Lombard' },
	{ code: 'lua', name: 'Luba-Kasai' },
	{ code: 'luo', name: 'Luo' },
	{ code: 'mk', name: 'Macedonian' },
	{ code: 'mag', name: 'Magahi' },
	{ code: 'mai', name: 'Maithili' },
	{ code: 'mg', name: 'Malagasy' },
	{ code: 'ms', name: 'Malay' },
	{ code: 'ml', name: 'Malayalam' },
	{ code: 'mt', name: 'Maltese' },
	{ code: 'mi', name: 'Māori' },
	{ code: 'mr', name: 'Marathi' },
	{ code: 'mni', name: 'Meitei' },
	{ code: 'min', name: 'Minangkabau' },
	{ code: 'lus', name: 'Mizo' },
	{ code: 'mn', name: 'Mongolian' },
	{ code: 'mos', name: 'Mossi' },
	{ code: 'ne', name: 'Nepali' },
	{ code: 'no', name: 'Norwegian (Bokmål)' },
	{ code: 'nn', name: 'Norwegian (Nynorsk)' },
	{ code: 'nso', name: 'Northern Sotho' },
	{ code: 'nus', name: 'Nuer' },
	{ code: 'ny', name: 'Nyanja' },
	{ code: 'oc', name: 'Occitan' },
	{ code: 'or', name: 'Odia' },
	{ code: 'om', name: 'Oromo' },
	{ code: 'pag', name: 'Pangasinan' },
	{ code: 'pap', name: 'Papiamento' },
	{ code: 'ps', name: 'Pashto' },
	{ code: 'fa', name: 'Persian' },
	{ code: 'pl', name: 'Polish' },
	{ code: 'pt', name: 'Portuguese' },
	{ code: 'pa', name: 'Punjabi' },
	{ code: 'qu', name: 'Quechua' },
	{ code: 'ro', name: 'Romanian' },
	{ code: 'rn', name: 'Rundi' },
	{ code: 'ru', name: 'Russian' },
	{ code: 'sg', name: 'Sango' },
	{ code: 'sa', name: 'Sanskrit' },
	{ code: 'sat', name: 'Santali' },
	{ code: 'sc', name: 'Sardinian' },
	{ code: 'gd', name: 'Scottish Gaelic' },
	{ code: 'sr', name: 'Serbian' },
	{ code: 'shn', name: 'Shan' },
	{ code: 'scn', name: 'Sicilian' },
	{ code: 'szl', name: 'Silesian' },
	{ code: 'sd', name: 'Sindhi' },
	{ code: 'si', name: 'Sinhala' },
	{ code: 'sk', name: 'Slovak' },
	{ code: 'sl', name: 'Slovenian' },
	{ code: 'sm', name: 'Samoan' },
	{ code: 'sn', name: 'Shona' },
	{ code: 'so', name: 'Somali' },
	{ code: 'st', name: 'Southern Sotho' },
	{ code: 'es', name: 'Spanish' },
	{ code: 'su', name: 'Sundanese' },
	{ code: 'sw', name: 'Swahili' },
	{ code: 'ss', name: 'Swati' },
	{ code: 'sv', name: 'Swedish' },
	{ code: 'tg', name: 'Tajik' },
	{ code: 'taq', name: 'Tamasheq' },
	{ code: 'zgh', name: 'Tamazight (Standard Moroccan)' },
	{ code: 'ta', name: 'Tamil' },
	{ code: 'tt', name: 'Tatar' },
	{ code: 'te', name: 'Telugu' },
	{ code: 'th', name: 'Thai' },
	{ code: 'ti', name: 'Tigrinya' },
	{ code: 'tpi', name: 'Tok Pisin' },
	{ code: 'tn', name: 'Tswana' },
	{ code: 'ts', name: 'Tsonga' },
	{ code: 'tk', name: 'Turkmen' },
	{ code: 'tum', name: 'Tumbuka' },
	{ code: 'tr', name: 'Turkish' },
	{ code: 'tw', name: 'Twi' },
	{ code: 'uk', name: 'Ukrainian' },
	{ code: 'umb', name: 'Umbundu' },
	{ code: 'ug', name: 'Uyghur' },
	{ code: 'ur', name: 'Urdu' },
	{ code: 'uz', name: 'Uzbek' },
	{ code: 'vec', name: 'Venetian' },
	{ code: 'vi', name: 'Vietnamese' },
	{ code: 'war', name: 'Waray' },
	{ code: 'cy', name: 'Welsh' },
	{ code: 'wo', name: 'Wolof' },
	{ code: 'xh', name: 'Xhosa' },
	{ code: 'yi', name: 'Yiddish' },
	{ code: 'yo', name: 'Yoruba' },
	{ code: 'zu', name: 'Zulu' },
] as const;

export const LANGUAGE_FORMATS = [
	{ value: 'bcp47', label: 'BCP-47' },
	{ value: 'native', label: 'Native' },
] as const;
